name: V2XR_AttFuse_with_MDD
root_dir: "/home/cse/Downloads/RL_3DOD/dataset_decompress/train"
validate_dir: "/home/cse/Downloads/RL_3DOD/dataset_decompress/val"
fov: True
train_sim: True
eval_sim: false
use_DeLidar: true
sim_weather: 'random' # '', '_fog_0.060', '_snow_2.5_2.0', or 'random' for random selection
use_camera: true # Enable camera data loading
weather_adaptive_fusion: true # Enable weather-adaptive camera fusion
use_camera_weighting: True

yaml_parser: "load_point_pillar_params"
train_params:
  batch_size: &batch_size 1
  epoches: 30
  eval_freq: 4
  save_freq: 1

fusion:
  core_method: 'IntermediateFusionDatasetV2XR' # LateFusionDataset, EarlyFusionDataset, IntermediateFusionDataset supported
  args: []

# Camera preprocessing parameters
camera:
  core_method: 'BaseCameraPreprocessor'
  args:
    resize: [224, 224]  # Resize camera images to this resolution
    normalize: true
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  # Camera to ego transformation
  cam_to_ego: true

# Weather classification parameters
weather_classifier:
  model_path: "/home/cse/Desktop/V2X-R/opencood/img_cls/models/img_cls_binary/best_epoch018_acc98.pth"  # Path to your trained weather classifier
  input_size: [224, 224]
  num_classes: 3  # normal, fog, snow
  weights:
    normal: 1.0
    fog: 0.3
    snow: 0.2

# preprocess-related
preprocess:
  # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  core_method: 'SpVoxelPreprocessor'
  args:
    voxel_size: &voxel_size [0.4, 0.4, 4]
    max_points_per_voxel: 32
    max_voxel_train: 32000
    max_voxel_test: 70000
  # lidar range for each individual cav.
  cav_lidar_range: &cav_lidar [-140.8, -40, -3, 140.8, 40, 1]

data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]

  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]

  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

# anchor box related
postprocess:
  core_method: 'VoxelPostprocessor' # VoxelPostprocessor, BevPostprocessor supported
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 3.9
    w: 1.6
    h: 1.56
    r: [0, 90]
    feature_stride: 2
    num: &achor_num 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.20
  order: 'hwl' # hwl or lwh
  max_num: 100 # maximum number of objects in a single frame. use this number to make sure different frames has the same dimension in the same batch
  nms_thresh: 0.15

# model related
model:
  core_method: point_pillar_intermediate_lrf_MDD
  args:
    voxel_size: *voxel_size
    lidar_range: *cav_lidar
    anchor_number: *achor_num
    use_camera: true  # Enable camera processing in model
    weather_adaptive: true  # Enable weather-adaptive fusion

    pillar_vfe:
      use_norm: true
      with_distance: false
      use_absolute_xyz: true
      num_filters: [64]
    point_pillar_scatter:
      num_features: 64

    # Camera backbone for feature extraction
    camera_backbone:
      core_method: 'ResNet18'  # Or your preferred backbone
      pretrained: true
      output_channels: 256

    # Weather classifier integration
    weather_classifier:
      enabled: true
      freeze_backbone: true  # Freeze pretrained weather classifier
      model_path: "/home/cse/Desktop/V2X-R/opencood/img_cls/models/img_cls_binary/best_epoch018_acc98.pth"
    mdd_block:
      model:
        in_channels: 64
        out_ch: 64
        ch: 8
        ch_mult: [1, 1]
        num_res_blocks: 2
        attn_resolutions: [16]
        dropout: 0.0
        resamp_with_conv: True
      diffusion:
        beta_schedule: linear
        beta_start: 0.0005
        beta_end: 0.02
        num_diffusion_timesteps: 3

    base_bev_backbone:
      layer_nums: [3, 5, 8]
      layer_strides: [2, 2, 2]
      num_filters: [128, 256, 512]
      upsample_strides: [1, 2, 4]
      num_upsample_filter: [128, 128, 128]
  
      compression: 0
    
    anchor_num: *achor_num

loss:
  core_method: point_pillar_loss_mdd
  args:
    cls_weight: 1.0
    reg: 2.0

optimizer:
  core_method: Adam
  lr: 0.002
  args:
    eps: 1e-10
    weight_decay: 1e-4

lr_scheduler:
  core_method: multistep #step, multistep and Exponential support
  gamma: 0.1
  step_size: [10, 15]
